name: Build Thermometer
on:
  push:
    paths: ["data/funds.json"]
  pull_request:
    paths: ["data/funds.json"]
permissions:
  contents: write
jobs:
  render:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.x"}
      - name: Render SVG
        run: python scripts/render_thermometer.py
      - name: Commit SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update thermometer.svg [skip ci]"
          file_pattern: "thermometer.svg"
